name: myrecipes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  go_router: ^13.2.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.7
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.4.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
